<<<<<<<< HEAD:manifests/opendatahub/base/roles/ds-pipeline-persistenceagent-role.yaml
========
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application-crd-id: data-science-pipelines
  name: ds-pipeline-persistenceagent-clusterrole
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources:
      - scheduledworkflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - taskruns
      - conditions
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
>>>>>>>> dc82a8d06 (Remove Namespace CLI flag in persistenceagent):manifests/opendatahub/base/clusterroles/ds-pipeline-persistenceagent-clusterrole.yaml
