apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application-crd-id: data-science-pipelines
<<<<<<<< HEAD:manifests/opendatahub/base/roles/ds-pipeline-persistenceagent-role.yaml
<<<<<<<< HEAD:manifests/opendatahub/base/clusterroles/ds-pipeline-persistenceagent-clusterrole.yaml
  name: ds-pipeline-persistenceagent-clusterrole
========
  name: ds-pipeline-persistenceagent-role
>>>>>>>> 00ef41620 (Rename manifests to Data Science Pipelines):manifests/opendatahub/base/roles/ds-pipeline-persistenceagent-role.yaml
========
  name: ds-pipeline-persistenceagent-clusterrole
>>>>>>>> 25de8e971 (Remove Namespace CLI flag in persistenceagent):manifests/opendatahub/base/clusterroles/ds-pipeline-persistenceagent-clusterrole.yaml
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources:
      - scheduledworkflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - taskruns
      - conditions
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
